### ISSUE TITLE
How generate globe points

### ISSUE THREAD

**Issue by farshadfahimi** [larsvers/d3-hexgrid#29]
I see the document, in the example part use `myPointLocationData` veriable and I didn't how to declare this.
I'm nubby on generate map and hexagon

I want to create a glob map that cover with the hexagon with 50km area, and I didn't how should I do this with hexgrid?

**Comment by larsvers** [comment]
The typical data structure for use with d3-hexgrid is point location data - an array of objects with at least latitude and longitude values as well as any additional data you might want to use for any additional information for each hexagon. Please see the [`markets` data in this Observable](https://observablehq.com/@larsvers/d3-hexgrid-examples#markets) as an example.
